/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  服务器返回上传文件的 url + token
    /// </summary>
    [Serializable]
    public partial class FileUploadResponse : Response
    {
        /// <summary>
        ///  上传文件的 url
        /// </summary>
        public string url;
        /// <summary>
        ///  上传文件的 token
        /// </summary>
        public string token;
        /// <summary>
        ///  空消息代表成功
        /// </summary>
        public string message;
        public override void OnRecycle()
        {
            base.OnRecycle();
            url = "";
            token = "";
            message = "";
        }
    }
}
